#!/bin/bash

count=10

: ' 
if (( $count < 9 )) # if condition using [ ] for compare integer , [[ ]] for compare String, ((  $count < 9  )) 
then
	#statements
	echo "the condition is true "
else
	echo "the condition is false"
fi'

: '
if [[ "$age" -gt 18 && "$age" -lt 40 ]]
then
	#statements
	echo "Age is correct"
else
	echo "Age is not correct"
fi'

age=25

if [ "$age" -gt 18 ] || [ "$age" -lt 40 ]
then
	#statements
	echo "Age is correct"
else
	echo "Age is not correct"
fi