#!/bin/bash

# ======= Diractory =======
#mkdir -p directory2
# read -p "Enter directory name to check : " direct

# if [ -d "$direct" ] # -d check folder have or not have
# then
# 	echo "$direct exists"
# else
# 	echo "$direct does't exist"
# fi

# ======= File =======

# ----- Create file -----
# read -p "Enter file name to create : " fileName
# touch "$fileName"

# ----- Check file name ------
# read -p "Enter file name to check : " fileName

# if [ -f "$fileName" ] # or [[ -f "$fileName" ]]  # -d check file have or not have
# then
# 	read -p "Enter the text that you want to append : " fileText
# 	echo "$fileText" >> "$fileName"
# else
# 	echo "$fileName does't exist"
# fi

# ----- Read text in file ------

# read -p "Enter filename from which you want to read  : " fileName

# if [ -f "$fileName" ] # or [[ -f "$fileName" ]]  # -d check file have or not have
# then
# 	while IFS="" read -r line
# 	do
# 		#statements
# 		echo "$line"
# 	done < $fileName
# else
# 	echo "$fileName does't exist"
# fi

# ----- Romove file ------

read -p "Enter filename from which you want to remove  : " fileName

if [ -f "$fileName" ] # or [[ -f "$fileName" ]]  # -d check file have or not have
then
	rm "$fileName"
	echo "file has been deleted successful"
else
	echo "$fileName does't exist"
fi
