#! /bin/bash

# MESSAGE="Hello LinuxHint Audience"
# export MESSAGE
# ./stringProcessing-2

read -p "Enter 1st string : " str1

# echo "Enter 2nd string"
read -p "Enter 2st string : " str2

echo "String 1 : $str1"
echo "String 2 : $str2"
echo "================================="
# if [ "$str1" = "$str2" ] # or [[ "$str1" == "$str2"  ]]  or [ "$str1" =  "$str2" ]
# then
# 	#statements
# 	echo "String match"
# else
# 	echo "Not match"
# fi

# if [ "$str1" \< "$str2" ] # or [[ "$str1" == "$str2"  ]]  or [ "$str1" =  "$str2" ]
# then
# 	#statements
# 	echo "In IF"
# 	echo "$str1 is smaller then $str2"
# elif [ "$str1" \> "$str2" ]
# then
# 	#statements
# 	echo "In ELIF"

# 	echo "$str2 is smaller then $str1"
# else
# 	echo "In ELSE"
# 	echo "Both string equal"
# fi

# ----- Concatenation -----
# c=$str1$str2
# echo $c

echo ${str1^l}
echo ${str1^^}
